remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Lambda Universal Router
description: A flexible and type-safe router for AWS Lambda functions
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
