title: Lambda Universal Router
description: A flexible and type-safe router for AWS Lambda functions
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

show_downloads: true
github:
  is_project_page: true
  repository_url: https://github.com/raumildhandhukia/lambda-universal-router
  repository_name: lambda-universal-router
  owner_name: Raumil Dhandhukia
  owner_url: https://github.com/raumildhandhukia